function [] = quitfun(arg1)
global figHndl
scrsize = get(0,'ScreenSize');
scrweidth = scrsize(3)-scrsize(1);
scrheigth = scrsize(4)-scrsize(2);
if nargin < 1
    arg1 = 'start';
end
if strcmp(arg1,'start')
    w = 224;
    h = 100;
    figure('Position',[(scrweidth-w)/2,(scrheigth-h)/2,w,h],...
        'Menubar','none',...
        'NumberTitle','off',...
        'Name','MCFDTools',...
        'Color',192/255*[1 1 1],...
        'Resize','off');
    uicontrol('Style','text',...
        'String','确认退出？',...
        'FontSize',10,...
        'Fontname','Microsoft YaHei',...
        'Units','normalized', ...
        'Position',[0.2,0.65,0.6,0.2],...
        'BackgroundColor',192/255*[1 1 1]);
    uicontrol('Style','pushbutton',...
        'String','确认',...
        'FontSize',10,...
        'Fontname','Microsoft YaHei',...
        'Units','normalized', ...
        'Position',[0.1,0.2,0.3,0.3],...
        'Callback','quitfun(''yes'')');
    uicontrol('Style','pushbutton',...
        'String','取消',...
        'FontSize',10,...
        'Fontname','Microsoft YaHei',...
        'Units','normalized', ...
        'Position',[0.6,0.2,0.3,0.3],...
        'Callback','quitfun(''no'')');
elseif strcmp(arg1,'yes')
    close(gcf);
    delete(figHndl);
elseif strcmp(arg1,'no')
    close(gcf)
end
    
end
