function [] = gridsolver(arg1)

%工作路径
global workpath figHndl 
%主程序
if nargin < 1
    arg1 = 'start';
end
if strcmp(arg1,'start')
    %清空图形界面
    set(figHndl,'Position',get(0,'DefaultFigurePosition'));
    clearfigure(figHndl)
    %----------------设置主界面-------------------%
    set(figHndl,'Name','MCFDTools-网格划分工具')
    %%
    %--------------------------------侧边控制按钮--------------------------------
    uicontrol( ...
        'Style','frame', ...
        'Units','normalized', ...
        'Position',[0.78,0.03,0.19,0.94], ...
        'BackgroundColor',[0.50 0.50 0.50]);
    uicontrol(...
        'Style','pushbutton', ...
        'Units','normalized', ...
        'Position',[0.8,0.8,0.15,0.1], ...
        'String','计算', ...
        'FontSize',10, ...
        'FontName','Microsoft YaHei', ...
        'Callback', 'gridsolver(''calculate'')');
    uicontrol(...
        'Style','pushbutton', ...
        'Units','normalized', ...
        'Position',[0.8,0.26,0.15,0.1], ...
        'String','关于', ...
        'FontSize',10, ...
        'FontName','Microsoft YaHei', ...
        'Callback', 'gridsolver(''about'')');
    uicontrol(...
        'Style','pushbutton', ...
        'Units','normalized', ...
        'Position',[0.8,0.1,0.15,0.1], ...
        'String','退出', ...
        'FontSize',10, ...
        'FontName','Microsoft YaHei', ...
        'Callback', 'gridsolver(''quit'')');
    
    %%
    %功能选择
    bgHndl = uibuttongroup(...
        'Visible','on',...
        'Position',[0.02 0.4 0.21 0.57],...
        'BackgroundColor',192/255*[1 1 1],...
        'Title','功能选择',...
        'FontSize',10,...
        'ForegroundColor','b',...
        'FontName','Microsoft YaHei');
    h = 0.15;
    w = 0.8;
    starth = 0.8;
    uicontrol(bgHndl,...
        'Style','radiobutton',...
        'String','功能一',...
        'Units','normalized', ...
        'BackgroundColor',192/255*[1 1 1],...
        'FontSize',10,...
        'ForegroundColor','k',...
        'FontName','Microsoft YaHei', ...
        'Position',[0.1,starth,w,h],...
        'Callback','gridsolver(''1'')');
    uicontrol(bgHndl,...
        'Style','radiobutton',...
        'String','功能二',...
        'Units','normalized', ...
        'BackgroundColor',192/255*[1 1 1],...
        'FontSize',10,...
        'ForegroundColor','k',...
        'FontName','Microsoft YaHei', ...
        'Position',[0.1,starth-h,w,h],...
        'Callback','gridsolver(''2'')');
    uicontrol(bgHndl,...
        'Style','radiobutton',...
        'String','功能三',...
        'Units','normalized', ...
        'BackgroundColor',192/255*[1 1 1],...
        'FontSize',10,...
        'ForegroundColor','k',...
        'FontName','Microsoft YaHei', ...
        'Position',[0.1,starth-h*2,w,h],...
        'Callback','gridsolver(''3'')');
    uicontrol(bgHndl,...
        'Style','radiobutton',...
        'String','功能四',...
        'Units','normalized', ...
        'BackgroundColor',192/255*[1 1 1],...
        'FontSize',10,...
        'ForegroundColor','k',...
        'FontName','Microsoft YaHei', ...
        'Position',[0.1,starth-h*3,w,h],...
        'Callback','gridsolver(''4'')');
    uicontrol(bgHndl,...
        'Style','radiobutton',...
        'String','功能五',...
        'Units','normalized', ...
        'BackgroundColor',192/255*[1 1 1],...
        'FontSize',10,...
        'ForegroundColor','k',...
        'FontName','Microsoft YaHei', ...
        'Position',[0.1,starth-h*4,w,h],...
        'Callback','gridsolver(''5'')');
    uicontrol(bgHndl,...
        'Style','radiobutton',...
        'String','Y+',...
        'Units','normalized', ...
        'BackgroundColor',192/255*[1 1 1],...
        'FontSize',10,...
        'ForegroundColor','k',...
        'FontName','Microsoft YaHei', ...
        'Position',[0.1,starth-h*5,w,h],...
        'Callback','gridsolver(''Y+'')');
    gridsolver('1');
    
    %%
    %功能说明
    h = 0.15;
    w = 0.98;
    starth = 0.8;
    space = 0.0;
    panelHndl = uipanel(figHndl,...
        'Title','功能说明', ...
        'BackgroundColor',192/255*[1 1 1],...
        'Units','normalized', ...
        'Position',[0.02,0.03,0.73,0.35],...
        'FontSize',10,...
        'ForegroundColor','b',...
        'FontName','Microsoft YaHei');
    uicontrol(panelHndl,...
        'Style','text',...
        'String','功能一:已知线段长度、第一层网格高度和最后一层网格高度，求解公比和网格数量',...
        'Units','normalized', ...
        'BackgroundColor',192/255*[1 1 1],...
        'FontSize',8,...
        'ForegroundColor','k',...
        'FontName','Microsoft YaHei', ...
        'Position',[0.05,starth,w,h],...
        'HorizontalAlignment','Left')
    uicontrol(panelHndl,...
        'Style','text',...
        'String','功能二:已知线段长度、第一层网格高度和网格数量，求解公比和最后一层网格高度',...
        'Units','normalized', ...
        'BackgroundColor',192/255*[1 1 1],...
        'FontSize',8,...
        'ForegroundColor','k',...
        'FontName','Microsoft YaHei', ...
        'Position',[0.05,starth-h-space,w,h],...
        'HorizontalAlignment','Left')
    uicontrol(panelHndl,...
        'Style','text',...
        'String','功能三:已知线段长度、第一层网格高度和公比，求解网格数量和最后一层网格高度',...
        'Units','normalized', ...
        'BackgroundColor',192/255*[1 1 1],...
        'FontSize',8,...
        'ForegroundColor','k',...
        'FontName','Microsoft YaHei', ...
        'Position',[0.05,starth-2*(h+space),w,h],...
        'HorizontalAlignment','Left')
    uicontrol(panelHndl,...
        'Style','text',...
        'String','功能四:已知线段长度、网格数量和公比，求解第一层网格高度和最后一层网格高度',...
        'Units','normalized', ...
        'BackgroundColor',192/255*[1 1 1],...
        'FontSize',8,...
        'ForegroundColor','k',...
        'FontName','Microsoft YaHei', ...
        'Position',[0.05,starth-3*(h+space),w,h],...
        'HorizontalAlignment','Left')
    uicontrol(panelHndl,...
        'Style','text',...
        'String','功能五:已知线段长度、边界层网格参数和最后一层网格高度，求解公比和网格数量',...
        'Units','normalized', ...
        'BackgroundColor',192/255*[1 1 1],...
        'FontSize',8,...
        'ForegroundColor','k',...
        'FontName','Microsoft YaHei', ...
        'Position',[0.05,starth-4*(h+space),w,h],...
        'HorizontalAlignment','Left')
    uicontrol(panelHndl,...
        'Style','text',...
        'String','Y+:根据流动特性求解第一层边界网格高度',...
        'Units','normalized', ...
        'BackgroundColor',192/255*[1 1 1],...
        'FontSize',8,...
        'ForegroundColor','k',...
        'FontName','Microsoft YaHei', ...
        'Position',[0.05,starth-5*(h+space),w,h],...
        'HorizontalAlignment','Left')
elseif strcmp(arg1,'1')
    filename = 'grid_1_configuration.mat';
    if filechecker(workpath,filename)
        load([workpath,'\',filename])
    else
        L = 10;
        l1 = 1;
        ln = 2;
    end
    delete(findall(allchild(figHndl),'Title','网格参数'))
    h = 0.12;
    w = 0.45;
    starth = 0.78;
    space = 0.02;
    panelHndl = uipanel(figHndl,...
        'Title','网格参数', ...
        'BackgroundColor',192/255*[1 1 1],...
        'Units','normalized', ...
        'Position',[0.25,0.4,0.5,0.57],...
        'FontSize',10,...
        'ForegroundColor','b',...
        'FontName','Microsoft YaHei');
    uicontrol(panelHndl,...
        'Style','text',...
        'String','线段长度:',...
        'BackgroundColor',192/255*[1 1 1],...
        'FontSize',10,...
        'ForegroundColor','k',...
        'FontName','Microsoft YaHei',...
        'Units','normalized', ...
        'Position',[0.03,starth,w,h],...
        'HorizontalAlignment','Left');
    uicontrol(panelHndl,...
        'Style','text',...
        'String','第一层网格高度:',...
        'BackgroundColor',192/255*[1 1 1],...
        'FontSize',10,...
        'ForegroundColor','k',...
        'FontName','Microsoft YaHei',...
        'Units','normalized', ...
        'Position',[0.03,starth-h-space,w,h],...
        'HorizontalAlignment','Left');
    uicontrol(panelHndl,...
        'Style','text',...
        'String','最后一层网格高度:',...
        'BackgroundColor',192/255*[1 1 1],...
        'FontSize',10,...
        'ForegroundColor','k',...
        'FontName','Microsoft YaHei',...
        'Units','normalized', ...
        'Position',[0.03,starth-2*(h+space),w,h],...
        'HorizontalAlignment','Left');
    uicontrol(panelHndl,...
        'Style','text',...
        'String','公比:',...
        'BackgroundColor',192/255*[1 1 1],...
        'FontSize',10,...
        'ForegroundColor','k',...
        'FontName','Microsoft YaHei',...
        'Units','normalized', ...
        'Position',[0.03,starth-3*(h+space),w,h],...
        'HorizontalAlignment','Left');
    uicontrol(panelHndl,...
        'Style','text',...
        'String','网格数量:',...
        'BackgroundColor',192/255*[1 1 1],...
        'FontSize',10,...
        'ForegroundColor','k',...
        'FontName','Microsoft YaHei',...
        'Units','normalized', ...
        'Position',[0.03,starth-4*(h+space),w,h],...
        'HorizontalAlignment','Left');
    uicontrol(panelHndl,...
        'Style','edit',...
        'String',num2str(L),...
        'BackgroundColor','w',...
        'FontSize',10,...
        'ForegroundColor','k',...
        'FontName','Microsoft YaHei',...
        'Units','normalized', ...
        'Position',[0.03+w,starth,w,h],...
        'HorizontalAlignment','Left',...
        'Tag','L',...
        'Callback','gridsolver(''calculate'')');
    uicontrol(panelHndl,...
        'Style','edit',...
        'String',num2str(l1),...
        'BackgroundColor','w',...
        'FontSize',10,...
        'ForegroundColor','k',...
        'FontName','Microsoft YaHei',...
        'Units','normalized', ...
        'Position',[0.03+w,starth-h-space,w,h],...
        'HorizontalAlignment','Left',...
        'Tag','l1',...
        'Callback','gridsolver(''calculate'')');
    uicontrol(panelHndl,...
        'Style','edit',...
        'String',num2str(ln),...
        'BackgroundColor','w',...
        'FontSize',10,...
        'ForegroundColor','k',...
        'FontName','Microsoft YaHei',...
        'Units','normalized', ...
        'Position',[0.03+w,starth-2*(h+space),w,h],...
        'HorizontalAlignment','Left',...
        'Tag','ln',...
        'Callback','gridsolver(''calculate'')');
    uicontrol(panelHndl,...
        'Style','edit',...
        'String','',...
        'BackgroundColor','w',...
        'FontSize',10,...
        'ForegroundColor','b',...
        'FontName','Microsoft YaHei',...
        'Units','normalized', ...
        'Position',[0.03+w,starth-3*(h+space),w,h],...
        'HorizontalAlignment','Left',...
        'Tag','r');
    uicontrol(panelHndl,...
        'Style','edit',...
        'String','',...
        'BackgroundColor','w',...
        'FontSize',10,...
        'ForegroundColor','b',...
        'FontName','Microsoft YaHei',...
        'Units','normalized', ...
        'Position',[0.03+w,starth-4*(h+space),w,h],...
        'HorizontalAlignment','Left',...
        'Tag','n');
    gridsolver('calculate');
    
elseif strcmp(arg1,'2')
    filename = 'grid_2_configuration.mat';
    if filechecker(workpath,filename)
        load([workpath,'\',filename])
    else
        L = 10;
        l1 = 1;
        n = 7;
    end
    delete(findall(allchild(figHndl),'Title','网格参数'))
    h = 0.12;
    w = 0.45;
    starth = 0.78;
    space = 0.02;
    panelHndl = uipanel(figHndl,...
        'Title','网格参数', ...
        'BackgroundColor',192/255*[1 1 1],...
        'Units','normalized', ...
        'Position',[0.25,0.4,0.5,0.57],...
        'FontSize',10,...
        'ForegroundColor','b',...
        'FontName','Microsoft YaHei');
    uicontrol(panelHndl,...
        'Style','text',...
        'String','线段长度:',...
        'BackgroundColor',192/255*[1 1 1],...
        'FontSize',10,...
        'ForegroundColor','k',...
        'FontName','Microsoft YaHei',...
        'Units','normalized', ...
        'Position',[0.03,starth,w,h],...
        'HorizontalAlignment','Left');
    uicontrol(panelHndl,...
        'Style','text',...
        'String','第一层网格高度:',...
        'BackgroundColor',192/255*[1 1 1],...
        'FontSize',10,...
        'ForegroundColor','k',...
        'FontName','Microsoft YaHei',...
        'Units','normalized', ...
        'Position',[0.03,starth-h-space,w,h],...
        'HorizontalAlignment','Left');
    uicontrol(panelHndl,...
        'Style','text',...
        'String','网格数量:',...
        'BackgroundColor',192/255*[1 1 1],...
        'FontSize',10,...
        'ForegroundColor','k',...
        'FontName','Microsoft YaHei',...
        'Units','normalized', ...
        'Position',[0.03,starth-2*(h+space),w,h],...
        'HorizontalAlignment','Left');
    uicontrol(panelHndl,...
        'Style','text',...
        'String','公比:',...
        'BackgroundColor',192/255*[1 1 1],...
        'FontSize',10,...
        'ForegroundColor','k',...
        'FontName','Microsoft YaHei',...
        'Units','normalized', ...
        'Position',[0.03,starth-3*(h+space),w,h],...
        'HorizontalAlignment','Left');
    uicontrol(panelHndl,...
        'Style','text',...
        'String','最后一层网格高度:',...
        'BackgroundColor',192/255*[1 1 1],...
        'FontSize',10,...
        'ForegroundColor','k',...
        'FontName','Microsoft YaHei',...
        'Units','normalized', ...
        'Position',[0.03,starth-4*(h+space),w,h],...
        'HorizontalAlignment','Left');
    uicontrol(panelHndl,...
        'Style','edit',...
        'String',num2str(L),...
        'BackgroundColor','w',...
        'FontSize',10,...
        'ForegroundColor','k',...
        'FontName','Microsoft YaHei',...
        'Units','normalized', ...
        'Position',[0.03+w,starth,w,h],...
        'HorizontalAlignment','Left',...
        'Tag','L',...
        'Callback','gridsolver(''calculate'')');
    uicontrol(panelHndl,...
        'Style','edit',...
        'String',num2str(l1),...
        'BackgroundColor','w',...
        'FontSize',10,...
        'ForegroundColor','k',...
        'FontName','Microsoft YaHei',...
        'Units','normalized', ...
        'Position',[0.03+w,starth-h-space,w,h],...
        'HorizontalAlignment','Left',...
        'Tag','l1',...
        'Callback','gridsolver(''calculate'')');
    uicontrol(panelHndl,...
        'Style','edit',...
        'String',num2str(n),...
        'BackgroundColor','w',...
        'FontSize',10,...
        'ForegroundColor','k',...
        'FontName','Microsoft YaHei',...
        'Units','normalized', ...
        'Position',[0.03+w,starth-2*(h+space),w,h],...
        'HorizontalAlignment','Left',...
        'Tag','n',...
        'Callback','gridsolver(''calculate'')');
    uicontrol(panelHndl,...
        'Style','edit',...
        'String','',...
        'BackgroundColor','w',...
        'FontSize',10,...
        'ForegroundColor','b',...
        'FontName','Microsoft YaHei',...
        'Units','normalized', ...
        'Position',[0.03+w,starth-3*(h+space),w,h],...
        'HorizontalAlignment','Left',...
        'Tag','r');
    uicontrol(panelHndl,...
        'Style','edit',...
        'String','',...
        'BackgroundColor','w',...
        'FontSize',10,...
        'ForegroundColor','b',...
        'FontName','Microsoft YaHei',...
        'Units','normalized', ...
        'Position',[0.03+w,starth-4*(h+space),w,h],...
        'HorizontalAlignment','Left',...
        'Tag','ln');
    gridsolver('calculate');
elseif strcmp(arg1,'3')
    filename = 'grid_3_configuration.mat';
    if filechecker(workpath,filename)
        load([workpath,'\',filename])
    else
        L = 10;
        l1 = 1;
        r = 1.25;
    end
    delete(findall(allchild(figHndl),'Title','网格参数'))
    h = 0.12;
    w = 0.45;
    starth = 0.78;
    space = 0.02;
    panelHndl = uipanel(figHndl,...
        'Title','网格参数', ...
        'BackgroundColor',192/255*[1 1 1],...
        'Units','normalized', ...
        'Position',[0.25,0.4,0.5,0.57],...
        'FontSize',10,...
        'ForegroundColor','b',...
        'FontName','Microsoft YaHei');
    uicontrol(panelHndl,...
        'Style','text',...
        'String','线段长度:',...
        'BackgroundColor',192/255*[1 1 1],...
        'FontSize',10,...
        'ForegroundColor','k',...
        'FontName','Microsoft YaHei',...
        'Units','normalized', ...
        'Position',[0.03,starth,w,h],...
        'HorizontalAlignment','Left');
    uicontrol(panelHndl,...
        'Style','text',...
        'String','第一层网格高度:',...
        'BackgroundColor',192/255*[1 1 1],...
        'FontSize',10,...
        'ForegroundColor','k',...
        'FontName','Microsoft YaHei',...
        'Units','normalized', ...
        'Position',[0.03,starth-h-space,w,h],...
        'HorizontalAlignment','Left');
    uicontrol(panelHndl,...
        'Style','text',...
        'String','公比:',...
        'BackgroundColor',192/255*[1 1 1],...
        'FontSize',10,...
        'ForegroundColor','k',...
        'FontName','Microsoft YaHei',...
        'Units','normalized', ...
        'Position',[0.03,starth-2*(h+space),w,h],...
        'HorizontalAlignment','Left');
    uicontrol(panelHndl,...
        'Style','text',...
        'String','网格数量:',...
        'BackgroundColor',192/255*[1 1 1],...
        'FontSize',10,...
        'ForegroundColor','k',...
        'FontName','Microsoft YaHei',...
        'Units','normalized', ...
        'Position',[0.03,starth-3*(h+space),w,h],...
        'HorizontalAlignment','Left');
    uicontrol(panelHndl,...
        'Style','text',...
        'String','最后一层网格高度:',...
        'BackgroundColor',192/255*[1 1 1],...
        'FontSize',10,...
        'ForegroundColor','k',...
        'FontName','Microsoft YaHei',...
        'Units','normalized', ...
        'Position',[0.03,starth-4*(h+space),w,h],...
        'HorizontalAlignment','Left');
    uicontrol(panelHndl,...
        'Style','edit',...
        'String',num2str(L),...
        'BackgroundColor','w',...
        'FontSize',10,...
        'ForegroundColor','k',...
        'FontName','Microsoft YaHei',...
        'Units','normalized', ...
        'Position',[0.03+w,starth,w,h],...
        'HorizontalAlignment','Left',...
        'Tag','L',...
        'Callback','gridsolver(''calculate'')');
    uicontrol(panelHndl,...
        'Style','edit',...
        'String',num2str(l1),...
        'BackgroundColor','w',...
        'FontSize',10,...
        'ForegroundColor','k',...
        'FontName','Microsoft YaHei',...
        'Units','normalized', ...
        'Position',[0.03+w,starth-h-space,w,h],...
        'HorizontalAlignment','Left',...
        'Tag','l1',...
        'Callback','gridsolver(''calculate'')');
    uicontrol(panelHndl,...
        'Style','edit',...
        'String',num2str(r),...
        'BackgroundColor','w',...
        'FontSize',10,...
        'ForegroundColor','k',...
        'FontName','Microsoft YaHei',...
        'Units','normalized', ...
        'Position',[0.03+w,starth-2*(h+space),w,h],...
        'HorizontalAlignment','Left',...
        'Tag','r',...
        'Callback','gridsolver(''calculate'')');
    uicontrol(panelHndl,...
        'Style','edit',...
        'String','',...
        'BackgroundColor','w',...
        'FontSize',10,...
        'ForegroundColor','b',...
        'FontName','Microsoft YaHei',...
        'Units','normalized', ...
        'Position',[0.03+w,starth-3*(h+space),w,h],...
        'HorizontalAlignment','Left',...
        'Tag','n');
    uicontrol(panelHndl,...
        'Style','edit',...
        'String','',...
        'BackgroundColor','w',...
        'FontSize',10,...
        'ForegroundColor','b',...
        'FontName','Microsoft YaHei',...
        'Units','normalized', ...
        'Position',[0.03+w,starth-4*(h+space),w,h],...
        'HorizontalAlignment','Left',...
        'Tag','ln');
    gridsolver('calculate');
elseif strcmp(arg1,'4')
    filename = 'grid_4_configuration.mat';
    if filechecker(workpath,filename)
        load([workpath,'\',filename])
    else
        L = 10;
        r = 1.125;
        n = 7;
    end
    delete(findall(allchild(figHndl),'Title','网格参数'))
    h = 0.12;
    w = 0.45;
    starth = 0.78;
    space = 0.02;
    panelHndl = uipanel(figHndl,...
        'Title','网格参数', ...
        'BackgroundColor',192/255*[1 1 1],...
        'Units','normalized', ...
        'Position',[0.25,0.4,0.5,0.57],...
        'FontSize',10,...
        'ForegroundColor','b',...
        'FontName','Microsoft YaHei');
    uicontrol(panelHndl,...
        'Style','text',...
        'String','线段长度:',...
        'BackgroundColor',192/255*[1 1 1],...
        'FontSize',10,...
        'ForegroundColor','k',...
        'FontName','Microsoft YaHei',...
        'Units','normalized', ...
        'Position',[0.03,starth,w,h],...
        'HorizontalAlignment','Left');
    uicontrol(panelHndl,...
        'Style','text',...
        'String','公比:',...
        'BackgroundColor',192/255*[1 1 1],...
        'FontSize',10,...
        'ForegroundColor','k',...
        'FontName','Microsoft YaHei',...
        'Units','normalized', ...
        'Position',[0.03,starth-h-space,w,h],...
        'HorizontalAlignment','Left');
    uicontrol(panelHndl,...
        'Style','text',...
        'String','网格数量:',...
        'BackgroundColor',192/255*[1 1 1],...
        'FontSize',10,...
        'ForegroundColor','k',...
        'FontName','Microsoft YaHei',...
        'Units','normalized', ...
        'Position',[0.03,starth-2*(h+space),w,h],...
        'HorizontalAlignment','Left');
    uicontrol(panelHndl,...
        'Style','text',...
        'String','第一层网格高度:',...
        'BackgroundColor',192/255*[1 1 1],...
        'FontSize',10,...
        'ForegroundColor','k',...
        'FontName','Microsoft YaHei',...
        'Units','normalized', ...
        'Position',[0.03,starth-3*(h+space),w,h],...
        'HorizontalAlignment','Left');
    uicontrol(panelHndl,...
        'Style','text',...
        'String','最后一层网格高度:',...
        'BackgroundColor',192/255*[1 1 1],...
        'FontSize',10,...
        'ForegroundColor','k',...
        'FontName','Microsoft YaHei',...
        'Units','normalized', ...
        'Position',[0.03,starth-4*(h+space),w,h],...
        'HorizontalAlignment','Left');
    uicontrol(panelHndl,...
        'Style','edit',...
        'String',num2str(L),...
        'BackgroundColor','w',...
        'FontSize',10,...
        'ForegroundColor','k',...
        'FontName','Microsoft YaHei',...
        'Units','normalized', ...
        'Position',[0.03+w,starth,w,h],...
        'HorizontalAlignment','Left',...
        'Tag','L',...
        'Callback','gridsolver(''calculate'')');
    uicontrol(panelHndl,...
        'Style','edit',...
        'String',num2str(r),...
        'BackgroundColor','w',...
        'FontSize',10,...
        'ForegroundColor','k',...
        'FontName','Microsoft YaHei',...
        'Units','normalized', ...
        'Position',[0.03+w,starth-h-space,w,h],...
        'HorizontalAlignment','Left',...
        'Tag','r',...
        'Callback','gridsolver(''calculate'')');
    uicontrol(panelHndl,...
        'Style','edit',...
        'String',num2str(n),...
        'BackgroundColor','w',...
        'FontSize',10,...
        'ForegroundColor','k',...
        'FontName','Microsoft YaHei',...
        'Units','normalized', ...
        'Position',[0.03+w,starth-2*(h+space),w,h],...
        'HorizontalAlignment','Left',...
        'Tag','n',...
        'Callback','gridsolver(''calculate'')');
    uicontrol(panelHndl,...
        'Style','edit',...
        'String','',...
        'BackgroundColor','w',...
        'FontSize',10,...
        'ForegroundColor','b',...
        'FontName','Microsoft YaHei',...
        'Units','normalized', ...
        'Position',[0.03+w,starth-3*(h+space),w,h],...
        'HorizontalAlignment','Left',...
        'Tag','l1');
    uicontrol(panelHndl,...
        'Style','edit',...
        'String','',...
        'BackgroundColor','w',...
        'FontSize',10,...
        'ForegroundColor','b',...
        'FontName','Microsoft YaHei',...
        'Units','normalized', ...
        'Position',[0.03+w,starth-4*(h+space),w,h],...
        'HorizontalAlignment','Left',...
        'Tag','ln');
    gridsolver('calculate');
elseif strcmp(arg1,'5')
    filename = 'grid_5_configuration.mat';
    if filechecker(workpath,filename)
        load([workpath,'\',filename])
    else
        L = 10;
        a = 0.01;
        ra = 1.2;
        na = 10;
        ln = 2;
    end
    delete(findall(allchild(figHndl),'Title','网格参数'))
    h = 0.12;
    w = 0.45;
    starth = 0.85;
    space = 0.02;
    panelHndl = uipanel(figHndl,...
        'Title','网格参数', ...
        'BackgroundColor',192/255*[1 1 1],...
        'Units','normalized', ...
        'Position',[0.25,0.4,0.5,0.57],...
        'FontSize',10,...
        'ForegroundColor','b',...
        'FontName','Microsoft YaHei');
    uicontrol(panelHndl,...
        'Style','text',...
        'String','线段长度:',...
        'BackgroundColor',192/255*[1 1 1],...
        'FontSize',10,...
        'ForegroundColor','k',...
        'FontName','Microsoft YaHei',...
        'Units','normalized', ...
        'Position',[0.03,starth,w,h],...
        'HorizontalAlignment','Left');
    uicontrol(panelHndl,...
        'Style','text',...
        'String','边界层网格高度:',...
        'BackgroundColor',192/255*[1 1 1],...
        'FontSize',10,...
        'ForegroundColor','k',...
        'FontName','Microsoft YaHei',...
        'Units','normalized', ...
        'Position',[0.03,starth-h-space,w,h],...
        'HorizontalAlignment','Left');
    uicontrol(panelHndl,...
        'Style','text',...
        'String','边界层网格公比:',...
        'BackgroundColor',192/255*[1 1 1],...
        'FontSize',10,...
        'ForegroundColor','k',...
        'FontName','Microsoft YaHei',...
        'Units','normalized', ...
        'Position',[0.03,starth-2*(h+space),w,h],...
        'HorizontalAlignment','Left');
    uicontrol(panelHndl,...
        'Style','text',...
        'String','边界层网格数量:',...
        'BackgroundColor',192/255*[1 1 1],...
        'FontSize',10,...
        'ForegroundColor','k',...
        'FontName','Microsoft YaHei',...
        'Units','normalized', ...
        'Position',[0.03,starth-3*(h+space),w,h],...
        'HorizontalAlignment','Left');
    uicontrol(panelHndl,...
        'Style','text',...
        'String','最后一层网格高度:',...
        'BackgroundColor',192/255*[1 1 1],...
        'FontSize',10,...
        'ForegroundColor','k',...
        'FontName','Microsoft YaHei',...
        'Units','normalized', ...
        'Position',[0.03,starth-4*(h+space),w,h],...
        'HorizontalAlignment','Left');
    uicontrol(panelHndl,...
        'Style','text',...
        'String','公比:',...
        'BackgroundColor',192/255*[1 1 1],...
        'FontSize',10,...
        'ForegroundColor','k',...
        'FontName','Microsoft YaHei',...
        'Units','normalized', ...
        'Position',[0.03,starth-5*(h+space),w,h],...
        'HorizontalAlignment','Left');
    uicontrol(panelHndl,...
        'Style','text',...
        'String','网格数量:',...
        'BackgroundColor',192/255*[1 1 1],...
        'FontSize',10,...
        'ForegroundColor','k',...
        'FontName','Microsoft YaHei',...
        'Units','normalized', ...
        'Position',[0.03,starth-6*(h+space),w,h],...
        'HorizontalAlignment','Left');
    uicontrol(panelHndl,...
        'Style','edit',...
        'String',num2str(L),...
        'BackgroundColor','w',...
        'FontSize',10,...
        'ForegroundColor','k',...
        'FontName','Microsoft YaHei',...
        'Units','normalized', ...
        'Position',[0.03+w,starth,w,h],...
        'HorizontalAlignment','Left',...
        'Tag','L',...
        'Callback','gridsolver(''calculate'')');
    uicontrol(panelHndl,...
        'Style','edit',...
        'String',num2str(a),...
        'BackgroundColor','w',...
        'FontSize',10,...
        'ForegroundColor','k',...
        'FontName','Microsoft YaHei',...
        'Units','normalized', ...
        'Position',[0.03+w,starth-h-space,w,h],...
        'HorizontalAlignment','Left',...
        'Tag','a',...
        'Callback','gridsolver(''calculate'')');
    uicontrol(panelHndl,...
        'Style','edit',...
        'String',num2str(ra),...
        'BackgroundColor','w',...
        'FontSize',10,...
        'ForegroundColor','k',...
        'FontName','Microsoft YaHei',...
        'Units','normalized', ...
        'Position',[0.03+w,starth-2*(h+space),w,h],...
        'HorizontalAlignment','Left',...
        'Tag','ra',...
        'Callback','gridsolver(''calculate'')');
    uicontrol(panelHndl,...
        'Style','edit',...
        'String',num2str(na),...
        'BackgroundColor','w',...
        'FontSize',10,...
        'ForegroundColor','k',...
        'FontName','Microsoft YaHei',...
        'Units','normalized', ...
        'Position',[0.03+w,starth-3*(h+space),w,h],...
        'HorizontalAlignment','Left',...
        'Tag','na',...
        'Callback','gridsolver(''calculate'')');
    uicontrol(panelHndl,...
        'Style','edit',...
        'String',num2str(ln),...
        'BackgroundColor','w',...
        'FontSize',10,...
        'ForegroundColor','k',...
        'FontName','Microsoft YaHei',...
        'Units','normalized', ...
        'Position',[0.03+w,starth-4*(h+space),w,h],...
        'HorizontalAlignment','Left',...
        'Tag','ln',...
        'Callback','gridsolver(''calculate'')');
    uicontrol(panelHndl,...
        'Style','edit',...
        'String','',...
        'BackgroundColor','w',...
        'FontSize',10,...
        'ForegroundColor','b',...
        'FontName','Microsoft YaHei',...
        'Units','normalized', ...
        'Position',[0.03+w,starth-5*(h+space),w,h],...
        'HorizontalAlignment','Left',...
        'Tag','r');
    uicontrol(panelHndl,...
        'Style','edit',...
        'String','',...
        'BackgroundColor','w',...
        'FontSize',10,...
        'ForegroundColor','b',...
        'FontName','Microsoft YaHei',...
        'Units','normalized', ...
        'Position',[0.03+w,starth-6*(h+space),w,h],...
        'HorizontalAlignment','Left',...
        'Tag','n');
    gridsolver('calculate');
elseif strcmp(arg1,'Y+')
    filename = 'Y+_configuration.mat';
    if filechecker(workpath,filename)
        load([workpath,'\',filename])
    else
        u = 100;
        density = 998.2;
        mu = 0.001003;
        L = 1;
        yplus = 30;
    end
    delete(findall(allchild(figHndl),'Title','网格参数'))
    h = 0.12;
    w = 0.45;
    starth = 0.78;
    space = 0.02;
    panelHndl = uipanel(figHndl,...
        'Title','网格参数', ...
        'BackgroundColor',192/255*[1 1 1],...
        'Units','normalized', ...
        'Position',[0.25,0.4,0.5,0.57],...
        'FontSize',10,...
        'ForegroundColor','b',...
        'FontName','Microsoft YaHei');
    uicontrol(panelHndl,...
        'Style','text',...
        'String','来流速度[m/s]:',...
        'BackgroundColor',192/255*[1 1 1],...
        'FontSize',10,...
        'ForegroundColor','k',...
        'FontName','Microsoft YaHei',...
        'Units','normalized', ...
        'Position',[0.03,starth,w,h],...
        'HorizontalAlignment','Left');
    uicontrol(panelHndl,...
        'Style','text',...
        'String','流体密度[kg/m3]:',...
        'BackgroundColor',192/255*[1 1 1],...
        'FontSize',10,...
        'ForegroundColor','k',...
        'FontName','Microsoft YaHei',...
        'Units','normalized', ...
        'Position',[0.03,starth-h-space,w,h],...
        'HorizontalAlignment','Left');
    uicontrol(panelHndl,...
        'Style','text',...
        'String','动力粘度[kg/m/s]:',...
        'BackgroundColor',192/255*[1 1 1],...
        'FontSize',10,...
        'ForegroundColor','k',...
        'FontName','Microsoft YaHei',...
        'Units','normalized', ...
        'Position',[0.03,starth-2*(h+space),w,h],...
        'HorizontalAlignment','Left');
    uicontrol(panelHndl,...
        'Style','text',...
        'String','特征长度[m]:',...
        'BackgroundColor',192/255*[1 1 1],...
        'FontSize',10,...
        'ForegroundColor','k',...
        'FontName','Microsoft YaHei',...
        'Units','normalized', ...
        'Position',[0.03,starth-3*(h+space),w,h],...
        'HorizontalAlignment','Left');
    uicontrol(panelHndl,...
        'Style','text',...
        'String','Y+[1]:',...
        'BackgroundColor',192/255*[1 1 1],...
        'FontSize',10,...
        'ForegroundColor','k',...
        'FontName','Microsoft YaHei',...
        'Units','normalized', ...
        'Position',[0.03,starth-4*(h+space),w,h],...
        'HorizontalAlignment','Left');
    uicontrol(panelHndl,...
        'Style','text',...
        'String','首层网格高度[mm]:',...
        'BackgroundColor',192/255*[1 1 1],...
        'FontSize',10,...
        'ForegroundColor','k',...
        'FontName','Microsoft YaHei',...
        'Units','normalized', ...
        'Position',[0.03,starth-5*(h+space),w,h],...
        'HorizontalAlignment','Left');
    uicontrol(panelHndl,...
        'Style','edit',...
        'String',num2str(u),...
        'BackgroundColor','w',...
        'FontSize',10,...
        'ForegroundColor','k',...
        'FontName','Microsoft YaHei',...
        'Units','normalized', ...
        'Position',[0.03+w,starth,w,h],...
        'HorizontalAlignment','Left',...
        'Tag','u',...
        'Callback','gridsolver(''calculate'')');
    uicontrol(panelHndl,...
        'Style','edit',...
        'String',num2str(density),...
        'BackgroundColor','w',...
        'FontSize',10,...
        'ForegroundColor','k',...
        'FontName','Microsoft YaHei',...
        'Units','normalized', ...
        'Position',[0.03+w,starth-h-space,w,h],...
        'HorizontalAlignment','Left',...
        'Tag','Density',...
        'Callback','gridsolver(''calculate'')');
    uicontrol(panelHndl,...
        'Style','edit',...
        'String',num2str(mu),...
        'BackgroundColor','w',...
        'FontSize',10,...
        'ForegroundColor','k',...
        'FontName','Microsoft YaHei',...
        'Units','normalized', ...
        'Position',[0.03+w,starth-2*(h+space),w,h],...
        'HorizontalAlignment','Left',...
        'Tag','mu',...
        'Callback','gridsolver(''calculate'')');
    uicontrol(panelHndl,...
        'Style','edit',...
        'String',num2str(L),...
        'BackgroundColor','w',...
        'FontSize',10,...
        'ForegroundColor','k',...
        'FontName','Microsoft YaHei',...
        'Units','normalized', ...
        'Position',[0.03+w,starth-3*(h+space),w,h],...
        'HorizontalAlignment','Left',...
        'Tag','L',...
        'Callback','gridsolver(''calculate'')');
    uicontrol(panelHndl,...
        'Style','edit',...
        'String',num2str(yplus),...
        'BackgroundColor','w',...
        'FontSize',10,...
        'ForegroundColor','k',...
        'FontName','Microsoft YaHei',...
        'Units','normalized', ...
        'Position',[0.03+w,starth-4*(h+space),w,h],...
        'HorizontalAlignment','Left',...
        'Tag','Yplus',...
        'Callback','gridsolver(''calculate'')');
    uicontrol(panelHndl,...
        'Style','edit',...
        'String','',...
        'BackgroundColor','w',...
        'FontSize',10,...
        'ForegroundColor','b',...
        'FontName','Microsoft YaHei',...
        'Units','normalized', ...
        'Position',[0.03+w,starth-5*(h+space),w,h],...
        'HorizontalAlignment','Left',...
        'Tag','Deltas');
    gridsolver('calculate');
elseif strcmp(arg1,'calculate')
    child = allchild(figHndl);
    select = findall(child,'Title','功能选择');
    fun = select.SelectedObject.String;
    switch fun
        case '功能一'
            LEdit = findall(child,'Tag','L');
            l1Edit = findall(child,'Tag','l1');
            lnEdit = findall(child,'Tag','ln');
            rEdit = findall(child,'Tag','r');
            nEdit = findall(child,'Tag','n');
            L = str2double(LEdit.String);
            l1 = str2double(l1Edit.String);
            ln = str2double(lnEdit.String);
            r = (L/l1-1)/(L/l1-ln/l1);
            if r == 1
                n = L/l1;
            else
                n = ceil(log(ln/l1)/log(r)+1);
            end
            rEdit.String = num2str(r);
            nEdit.String = num2str(n);
            filename = 'grid_1_configuration.mat';
            save([workpath,'\',filename],'L','l1','ln');
        case '功能二'
            LEdit = findall(child,'Tag','L');
            l1Edit = findall(child,'Tag','l1');
            lnEdit = findall(child,'Tag','ln');
            rEdit = findall(child,'Tag','r');
            nEdit = findall(child,'Tag','n');
            L = str2double(LEdit.String);
            l1 = str2double(l1Edit.String);
            n = str2double(nEdit.String);
            coef = zeros(1,n+1);
            coef(1) = 1;
            coef(n) = -L/l1;
            coef(n+1) = L/l1-1;
            r = roots(coef);
            realr = real(r);
            imagr = imag(r);
            rs = realr(imagr == 0);
            rs = rs(rs ~= 1);
            r = rs(rs > 0);
            [~,index] = max(abs(r-1));
            r = r(index);
            ln = l1*r^(n-1);
            rEdit.String = num2str(r);
            lnEdit.String = num2str(ln);
            filename = 'grid_2_configuration.mat';
            save([workpath,'\',filename],'L','l1','n');
        case '功能三'
            LEdit = findall(child,'Tag','L');
            l1Edit = findall(child,'Tag','l1');
            lnEdit = findall(child,'Tag','ln');
            rEdit = findall(child,'Tag','r');
            nEdit = findall(child,'Tag','n');
            L = str2double(LEdit.String);
            l1 = str2double(l1Edit.String);
            r = str2double(rEdit.String);
            n = ceil(log(1-L/l1*(1-r))/log(r));
            ln = l1*r^(n-1);
            nEdit.String = num2str(n);
            lnEdit.String = num2str(ln);
            filename = 'grid_3_configuration.mat';
            save([workpath,'\',filename],'L','l1','r');
        case '功能四'
            LEdit = findall(child,'Tag','L');
            l1Edit = findall(child,'Tag','l1');
            lnEdit = findall(child,'Tag','ln');
            rEdit = findall(child,'Tag','r');
            nEdit = findall(child,'Tag','n');
            L = str2double(LEdit.String); 
            r = str2double(rEdit.String);
            n = str2double(nEdit.String);
            if r == 1
                l1 = L/n;
                ln = L/n;
            else
                l1 = L*(1-r)/(1-r^n);
                ln = l1*r^(n-1);
            end
            l1Edit.String = num2str(l1);
            lnEdit.String = num2str(ln);
            filename = 'grid_4_configuration.mat';
            save([workpath,'\',filename],'L','r','n');
        case '功能五'
            LEdit = findall(child,'Tag','L');
            aEdit = findall(child,'Tag','a');
            raEdit = findall(child,'Tag','ra');
            naEdit = findall(child,'Tag','na');
            lnEdit = findall(child,'Tag','ln');
            rEdit = findall(child,'Tag','r');
            nEdit = findall(child,'Tag','n');
            L = str2double(LEdit.String); 
            a = str2double(aEdit.String); 
            ra = str2double(raEdit.String);
            na = str2double(naEdit.String);
            ln = str2double(lnEdit.String);
            l1 = a*ra^na;
            Ltemp = L - a*(1-ra^(na-1))/(1-ra);
            r = (Ltemp/l1-1)/(Ltemp/l1-ln/l1);
            if r == 1
                n = Ltemp/l1 + na;
            else
                n = ceil(log(ln/l1)/log(r)+1) + na;
            end
            rEdit.String = num2str(r);
            nEdit.String = num2str(n);
            filename = 'grid_5_configuration.mat';
            save([workpath,'\',filename],'L','a','ra','na','ln');
        case 'Y+'
            uEdit = findall(child,'Tag','u');
            densityEdit = findall(child,'Tag','Density');
            muEdit = findall(child,'Tag','mu');
            LEdit = findall(child,'Tag','L');
            yplusEdit = findall(child,'Tag','Yplus');
            deltasEdit = findall(child,'Tag','Deltas');
            u = str2double(uEdit.String);
            density = str2double(densityEdit.String);
            mu = str2double(muEdit.String);
            L = str2double(LEdit.String);
            yplus = str2double(yplusEdit.String);
            Re_x = density*u*L/mu;
            C_f = 0.026/Re_x^(1/7);
            tao_wall = C_f*density*u^2/2;
            U_fric = sqrt(tao_wall/density);
            deltas = yplus*mu/U_fric/density;
            deltasEdit.String = num2str(deltas*1000);
            filename = 'Y+_configuration.mat';
            save([workpath,'\',filename],'u','density','mu','L','yplus');
    end
elseif strcmp(arg1,'quit')
    clearfigure(figHndl)
    figHndl.Name = 'MCFDTools';
end

end