function [] = masssolver(arg1)
%MASSSOLVER 规则几何体质量计算程序


%工作路径
global workpath figHndl 
%主程序
if nargin < 1
    arg1 = 'start';
end
if strcmp(arg1,'start')
    %清空图形界面
    set(figHndl,'Position',get(0,'DefaultFigurePosition'));
    clearfigure(figHndl)
    %----------------设置主界面-------------------%
    set(figHndl,'Name','MCFDTools-质量计算')
    %侧边控制按钮
    uicontrol( ...
        'Style','frame', ...
        'Units','normalized', ...
        'Position',[0.78,0.03,0.19,0.94], ...
        'BackgroundColor',[0.50 0.50 0.50]);
    uicontrol(...
        'Style','pushbutton', ...
        'Units','normalized', ...
        'Position',[0.8,0.8,0.15,0.1], ...
        'String','计算', ...
        'FontSize',10, ...
        'FontName','Microsoft YaHei', ...
        'Callback', 'masssolver(''calculate'')');
    uicontrol(...
        'Style','pushbutton', ...
        'Units','normalized', ...
        'Position',[0.8,0.26,0.15,0.1], ...
        'String','关于', ...
        'FontSize',10, ...
        'FontName','Microsoft YaHei', ...
        'Callback', 'masssolver(''about'')');
    uicontrol(...
        'Style','pushbutton', ...
        'Units','normalized', ...
        'Position',[0.8,0.1,0.15,0.1], ...
        'String','退出', ...
        'FontSize',10, ...
        'FontName','Microsoft YaHei', ...
        'Callback', 'masssolver(''quit'')');
    %形状选择
    bgHndl = uibuttongroup(...
        'Visible','on',...
        'Position',[0.02 0.4 0.21 0.57],...
        'BackgroundColor',192/255*[1 1 1],...
        'Title','外形选择',...
        'FontSize',10,...
        'ForegroundColor','b',...
        'FontName','Microsoft YaHei');
    h = 0.15;
    w = 0.8;
    starth = 0.8;
    uicontrol(bgHndl,...
        'Style','radiobutton',...
        'String','球体',...
        'Units','normalized', ...
        'BackgroundColor',192/255*[1 1 1],...
        'FontSize',10,...
        'ForegroundColor','k',...
        'FontName','Microsoft YaHei', ...
        'Position',[0.1,starth,w,h],...
        'Callback','masssolver(''sphere'')');
    uicontrol(bgHndl,...
        'Style','radiobutton',...
        'String','柱体',...
        'Units','normalized', ...
        'BackgroundColor',192/255*[1 1 1],...
        'FontSize',10,...
        'ForegroundColor','k',...
        'FontName','Microsoft YaHei', ...
        'Position',[0.1,starth-h,w,h],...
        'Callback','masssolver(''cylinder'')');
    uicontrol(bgHndl,...
        'Style','radiobutton',...
        'String','圆台',...
        'Units','normalized', ...
        'BackgroundColor',192/255*[1 1 1],...
        'FontSize',10,...
        'ForegroundColor','k',...
        'FontName','Microsoft YaHei', ...
        'Position',[0.1,starth-h*2,w,h],...
        'Callback','masssolver(''circle'')');
    uicontrol(bgHndl,...
        'Style','radiobutton',...
        'String','椎体',...
        'Units','normalized', ...
        'BackgroundColor',192/255*[1 1 1],...
        'FontSize',10,...
        'ForegroundColor','k',...
        'FontName','Microsoft YaHei', ...
        'Position',[0.1,starth-h*3,w,h],...
        'Callback','masssolver(''cone'')');
    uicontrol(bgHndl,...
        'Style','radiobutton',...
        'String','椎头圆柱体',...
        'Units','normalized', ...
        'BackgroundColor',192/255*[1 1 1],...
        'FontSize',10,...
        'ForegroundColor','k',...
        'FontName','Microsoft YaHei', ...
        'Position',[0.1,starth-h*4,w,h],...
        'Callback','masssolver(''cone_cylinder'')');
    uicontrol(bgHndl,...
        'Style','radiobutton',...
        'String','球头圆柱体',...
        'Units','normalized', ...
        'BackgroundColor',192/255*[1 1 1],...
        'FontSize',10,...
        'ForegroundColor','k',...
        'FontName','Microsoft YaHei', ...
        'Position',[0.1,starth-h*5,w,h],...
        'Callback','masssolver(''sphere_cylinder'')');
    %物体参数
    masssolver('sphere');
    %计算结果
    h = 0.1954285714;
    w = 0.2;
    starth = 0.7;
    space = 0.1;
    panelHndl = uipanel(figHndl,...
        'Title','计算结果', ...
        'BackgroundColor',192/255*[1 1 1],...
        'Units','normalized', ...
        'Position',[0.02,0.03,0.73,0.35],...
        'FontSize',10,...
        'ForegroundColor','b',...
        'FontName','Microsoft YaHei');
    uicontrol(panelHndl,...
        'Style','text',...
        'String','体积[m3]:',...
        'Units','normalized', ...
        'BackgroundColor',192/255*[1 1 1],...
        'FontSize',10,...
        'ForegroundColor','k',...
        'FontName','Microsoft YaHei', ...
        'Position',[0.05,starth,w,h],...
        'HorizontalAlignment','Left')
    uicontrol(panelHndl,...
        'Style','text',...
        'String','质量[kg]:',...
        'Units','normalized', ...
        'BackgroundColor',192/255*[1 1 1],...
        'FontSize',10,...
        'ForegroundColor','k',...
        'FontName','Microsoft YaHei', ...
        'Position',[0.05,starth-h-space,w,h],...
        'HorizontalAlignment','Left')
    uicontrol(panelHndl,...
        'Style','edit',...
        'String','',...
        'Units','normalized', ...
        'BackgroundColor','w',...
        'FontSize',10,...
        'ForegroundColor','k',...
        'FontName','Microsoft YaHei', ...
        'Position',[0.05+w,starth,w*2,h],...
        'HorizontalAlignment','Left',...
        'Tag','Volume')
    uicontrol(panelHndl,...
        'Style','edit',...
        'String','',...
        'Units','normalized', ...
        'BackgroundColor','w',...
        'FontSize',10,...
        'ForegroundColor','k',...
        'FontName','Microsoft YaHei', ...
        'Position',[0.05+w,starth-h-space,w*2,h],...
        'HorizontalAlignment','Left',...
        'Tag','Mass')
    
elseif strcmp(arg1,'calculate')
    %--------------------计算执行----------------------%
    child = allchild(figHndl);
    select = findall(child,'Title','外形选择');
    shape = select.SelectedObject.String;
    if strcmp(shape,'球体')
        diameterEdit = findall(child,'Tag','Diameter');
        densityEdit = findall(child,'Tag','Density');
        volumeEdit = findall(child,'Tag','Volume');
        massEdit =  findall(child,'Tag','Mass');
        diameter = str2double(diameterEdit.String);
        density = str2double(densityEdit.String);
        volume = 4/3*pi*(diameter/2)^3;
        mass = volume*density;
        volumeEdit.String = num2str(volume);
        massEdit.String = num2str(mass);
        filename = 'sphere_configuration.mat';
        save([workpath,'\',filename],'diameter','density');
    elseif strcmp(shape,'柱体')
        diameterEdit = findall(child,'Tag','Diameter');
        heightEdit = findall(child,'Tag','Height');
        densityEdit = findall(child,'Tag','Density');
        volumeEdit = findall(child,'Tag','Volume');
        massEdit =  findall(child,'Tag','Mass');
        diameter = str2double(diameterEdit.String);
        height = str2double(heightEdit.String);
        density = str2double(densityEdit.String);
        volume = pi*(diameter/2)^2*height;
        mass = volume*density;
        volumeEdit.String = num2str(volume);
        massEdit.String = num2str(mass);
        filename = 'cylinder_configuration.mat';
        save([workpath,'\',filename],'diameter','height','density');
    elseif strcmp(shape,'圆台')
        upDiameterEdit = findall(child,'Tag','UpDiameter');
        downDiameterEdit = findall(child,'Tag','DownDiameter');
        heightEdit = findall(child,'Tag','Height');
        densityEdit = findall(child,'Tag','Density');
        volumeEdit = findall(child,'Tag','Volume');
        massEdit =  findall(child,'Tag','Mass');
        upDiameter = str2double(upDiameterEdit.String);
        downDiameter = str2double(downDiameterEdit.String);
        height = str2double(heightEdit.String);
        density = str2double(densityEdit.String);
        volume = 1/3*pi*height*((upDiameter/2)^2+(downDiameter/2)^2+(upDiameter/2)*(downDiameter/2));
        mass = volume*density;
        volumeEdit.String = num2str(volume);
        massEdit.String = num2str(mass);
        filename = 'circle_configuration.mat';
        save([workpath,'\',filename],'upDiameter','downDiameter','height','density');
    elseif strcmp(shape,'椎体')
        diameterEdit = findall(child,'Tag','Diameter');
        tapeAngleEdit = findall(child,'Tag','TapeAngle');
        densityEdit = findall(child,'Tag','Density');
        volumeEdit = findall(child,'Tag','Volume');
        massEdit =  findall(child,'Tag','Mass');
        diameter = str2double(diameterEdit.String);
        tapeAngle = str2double(tapeAngleEdit.String);
        density = str2double(densityEdit.String);
        volume = 1/3*pi*(diameter/2)^2*(diameter/2)/tand(tapeAngle/2);
        mass = volume*density;
        volumeEdit.String = num2str(volume);
        massEdit.String = num2str(mass);
        filename = 'cone_configuration.mat';
        save([workpath,'\',filename],'diameter','tapeAngle','density');
    elseif strcmp(shape,'锥头圆柱体')
        diameterEdit = findall(child,'Tag','Diameter');
        heightEdit = findall(child,'Tag','Height');
        tapeAngleEdit = findall(child,'Tag','TapeAngle');
        densityEdit = findall(child,'Tag','Density');
        volumeEdit = findall(child,'Tag','Volume');
        massEdit =  findall(child,'Tag','Mass');
        diameter = str2double(diameterEdit.String);
        height = str2double(heightEdit.String);
        tapeAngle = str2double(tapeAngleEdit.String);
        density = str2double(densityEdit.String);
        volume = pi*(diameter/2)^2*height+1/3*pi*(diameter/2)^2*(diameter/2)/tand(tapeAngle/2);
        mass = volume*density;
        volumeEdit.String = num2str(volume);
        massEdit.String = num2str(mass);
        filename = 'cone_cylinder_configuration.mat';
        save([workpath,'\',filename],'diameter','height','tapeAngle','density');
    elseif strcmp(shape,'球头圆柱体')
        diameterEdit = findall(child,'Tag','Diameter');
        heightEdit = findall(child,'Tag','Height');
        densityEdit = findall(child,'Tag','Density');
        volumeEdit = findall(child,'Tag','Volume');
        massEdit =  findall(child,'Tag','Mass');
        diameter = str2double(diameterEdit.String);
        height = str2double(heightEdit.String);
        density = str2double(densityEdit.String);
        volume = pi*(diameter/2)^2*height+2/3*pi*(diameter/2)^3;
        mass = volume*density;
        volumeEdit.String = num2str(volume);
        massEdit.String = num2str(mass);
        filename = 'sphere_cylinder_configuration.mat';
        save([workpath,'\',filename],'diameter','height','density');
    end
    
elseif strcmp(arg1,'about')
    doc('masssolver')
    
elseif strcmp(arg1,'quit')
    clearfigure(figHndl)
    figHndl.Name = 'MCFDTools';
elseif strcmp(arg1,'sphere')
    filename = 'sphere_configuration.mat';
    if filechecker(workpath,filename)
        load([workpath,'\',filename])
    else
        diameter = 1;
        density = 7800;
    end
    delete(findall(allchild(figHndl),'Title','物体参数'))
    h = 0.12;
    w = 0.45;
    starth = 0.78;
    space = 0.1;
    panelHndl = uipanel(figHndl,...
        'Title','物体参数', ...
        'BackgroundColor',192/255*[1 1 1],...
        'Units','normalized', ...
        'Position',[0.25,0.4,0.5,0.57],...
        'FontSize',10,...
        'ForegroundColor','b',...
        'FontName','Microsoft YaHei');
    uicontrol(panelHndl,...
        'Style','text',...
        'String','球体直径[m]:',...
        'BackgroundColor',192/255*[1 1 1],...
        'FontSize',10,...
        'ForegroundColor','k',...
        'FontName','Microsoft YaHei',...
        'Units','normalized', ...
        'Position',[0.03,starth,w,h],...
        'HorizontalAlignment','Left');
    uicontrol(panelHndl,...
        'Style','text',...
        'String','球体密度[kg/m3]:',...
        'BackgroundColor',192/255*[1 1 1],...
        'FontSize',10,...
        'ForegroundColor','k',...
        'FontName','Microsoft YaHei',...
        'Units','normalized', ...
        'Position',[0.03,starth-h-space,w,h],...
        'HorizontalAlignment','Left');
    uicontrol(panelHndl,...
        'Style','edit',...
        'String',num2str(diameter),...
        'BackgroundColor','w',...
        'FontSize',10,...
        'ForegroundColor','k',...
        'FontName','Microsoft YaHei',...
        'Units','normalized', ...
        'Position',[0.03+w,starth,w,h],...
        'HorizontalAlignment','Left',...
        'Tag','Diameter');
    uicontrol(panelHndl,...
        'Style','edit',...
        'String',num2str(density),...
        'BackgroundColor','w',...
        'FontSize',10,...
        'ForegroundColor','k',...
        'FontName','Microsoft YaHei',...
        'Units','normalized', ...
        'Position',[0.03+w,starth-h-space,w,h],...
        'HorizontalAlignment','Left',...
        'Tag','Density');
elseif strcmp(arg1,'cylinder')
    filename = 'cylinder_configuration.mat';
    if filechecker(workpath,filename)
        load([workpath,'\',filename])
    else
        diameter = 1;
        height = 1;
        density = 7800;
    end
    delete(findall(allchild(figHndl),'Title','物体参数'))
    h = 0.12;
    w = 0.45;
    starth = 0.78;
    space = 0.1;
    panelHndl = uipanel(figHndl,...
        'Title','物体参数', ...
        'BackgroundColor',192/255*[1 1 1],...
        'Units','normalized', ...
        'Position',[0.25,0.4,0.5,0.57],...
        'FontSize',10,...
        'ForegroundColor','b',...
        'FontName','Microsoft YaHei');
    uicontrol(panelHndl,...
        'Style','text',...
        'String','柱体直径[m]:',...
        'BackgroundColor',192/255*[1 1 1],...
        'FontSize',10,...
        'ForegroundColor','k',...
        'FontName','Microsoft YaHei',...
        'Units','normalized', ...
        'Position',[0.03,starth,w,h],...
        'HorizontalAlignment','Left');
    uicontrol(panelHndl,...
        'Style','text',...
        'String','柱体高度[m]:',...
        'BackgroundColor',192/255*[1 1 1],...
        'FontSize',10,...
        'ForegroundColor','k',...
        'FontName','Microsoft YaHei',...
        'Units','normalized', ...
        'Position',[0.03,starth-h-space,w,h],...
        'HorizontalAlignment','Left');
    uicontrol(panelHndl,...
        'Style','text',...
        'String','柱体密度[kg/m3]:',...
        'BackgroundColor',192/255*[1 1 1],...
        'FontSize',10,...
        'ForegroundColor','k',...
        'FontName','Microsoft YaHei',...
        'Units','normalized', ...
        'Position',[0.03,starth-h*2-space*2,w,h],...
        'HorizontalAlignment','Left');
    uicontrol(panelHndl,...
        'Style','edit',...
        'String',num2str(diameter),...
        'BackgroundColor','w',...
        'FontSize',10,...
        'ForegroundColor','k',...
        'FontName','Microsoft YaHei',...
        'Units','normalized', ...
        'Position',[0.03+w,starth,w,h],...
        'HorizontalAlignment','Left',...
        'Tag','Diameter');
    uicontrol(panelHndl,...
        'Style','edit',...
        'String',num2str(height),...
        'BackgroundColor','w',...
        'FontSize',10,...
        'ForegroundColor','k',...
        'FontName','Microsoft YaHei',...
        'Units','normalized', ...
        'Position',[0.03+w,starth-h-space,w,h],...
        'HorizontalAlignment','Left',...
        'Tag','Height');
    uicontrol(panelHndl,...
        'Style','edit',...
        'String',num2str(density),...
        'BackgroundColor','w',...
        'FontSize',10,...
        'ForegroundColor','k',...
        'FontName','Microsoft YaHei',...
        'Units','normalized', ...
        'Position',[0.03+w,starth-h*2-space*2,w,h],...
        'HorizontalAlignment','Left',...
        'Tag','Density');
elseif strcmp(arg1,'circle')
    filename = 'circle_configuration.mat';
    if filechecker(workpath,filename)
        load([workpath,'\',filename])
    else
        upDiameter = 0.5;
        downDiameter = 1.5;
        height = 1;
        density = 7800;
    end
    delete(findall(allchild(figHndl),'Title','物体参数'))
    h = 0.12;
    w = 0.45;
    starth = 0.78;
    space = 0.1;
    panelHndl = uipanel(figHndl,...
        'Title','物体参数', ...
        'BackgroundColor',192/255*[1 1 1],...
        'Units','normalized', ...
        'Position',[0.25,0.4,0.5,0.57],...
        'FontSize',10,...
        'ForegroundColor','b',...
        'FontName','Microsoft YaHei');
    uicontrol(panelHndl,...
        'Style','text',...
        'String','圆台上直径[m]:',...
        'BackgroundColor',192/255*[1 1 1],...
        'FontSize',10,...
        'ForegroundColor','k',...
        'FontName','Microsoft YaHei',...
        'Units','normalized', ...
        'Position',[0.03,starth,w,h],...
        'HorizontalAlignment','Left');
    uicontrol(panelHndl,...
        'Style','text',...
        'String','圆台下直径[m]:',...
        'BackgroundColor',192/255*[1 1 1],...
        'FontSize',10,...
        'ForegroundColor','k',...
        'FontName','Microsoft YaHei',...
        'Units','normalized', ...
        'Position',[0.03,starth-h-space,w,h],...
        'HorizontalAlignment','Left');
    uicontrol(panelHndl,...
        'Style','text',...
        'String','圆台高度[m]:',...
        'BackgroundColor',192/255*[1 1 1],...
        'FontSize',10,...
        'ForegroundColor','k',...
        'FontName','Microsoft YaHei',...
        'Units','normalized', ...
        'Position',[0.03,starth-h*2-space*2,w,h],...
        'HorizontalAlignment','Left');
    uicontrol(panelHndl,...
        'Style','text',...
        'String','圆台密度[kg/m3]:',...
        'BackgroundColor',192/255*[1 1 1],...
        'FontSize',10,...
        'ForegroundColor','k',...
        'FontName','Microsoft YaHei',...
        'Units','normalized', ...
        'Position',[0.03,starth-h*3-space*3,w,h],...
        'HorizontalAlignment','Left');
    uicontrol(panelHndl,...
        'Style','edit',...
        'String',num2str(upDiameter),...
        'BackgroundColor','w',...
        'FontSize',10,...
        'ForegroundColor','k',...
        'FontName','Microsoft YaHei',...
        'Units','normalized', ...
        'Position',[0.03+w,starth,w,h],...
        'HorizontalAlignment','Left',...
        'Tag','UpDiameter');
    uicontrol(panelHndl,...
        'Style','edit',...
        'String',num2str(downDiameter),...
        'BackgroundColor','w',...
        'FontSize',10,...
        'ForegroundColor','k',...
        'FontName','Microsoft YaHei',...
        'Units','normalized', ...
        'Position',[0.03+w,starth-h-space,w,h],...
        'HorizontalAlignment','Left',...
        'Tag','DownDiameter');
    uicontrol(panelHndl,...
        'Style','edit',...
        'String',num2str(height),...
        'BackgroundColor','w',...
        'FontSize',10,...
        'ForegroundColor','k',...
        'FontName','Microsoft YaHei',...
        'Units','normalized', ...
        'Position',[0.03+w,starth-h*2-space*2,w,h],...
        'HorizontalAlignment','Left',...
        'Tag','Height');
    uicontrol(panelHndl,...
        'Style','edit',...
        'String',num2str(density),...
        'BackgroundColor','w',...
        'FontSize',10,...
        'ForegroundColor','k',...
        'FontName','Microsoft YaHei',...
        'Units','normalized', ...
        'Position',[0.03+w,starth-h*3-space*3,w,h],...
        'HorizontalAlignment','Left',...
        'Tag','Density');
elseif strcmp(arg1,'cone')
    filename = 'cone_configuration.mat';
    if filechecker(workpath,filename)
        load([workpath,'\',filename])
    else
        diameter = 1;
        tapeAngle = 90;
        density = 7800;
    end
    delete(findall(allchild(figHndl),'Title','物体参数'))
    h = 0.12;
    w = 0.45;
    starth = 0.78;
    space = 0.1;
    panelHndl = uipanel(figHndl,...
        'Title','物体参数', ...
        'BackgroundColor',192/255*[1 1 1],...
        'Units','normalized', ...
        'Position',[0.25,0.4,0.5,0.57],...
        'FontSize',10,...
        'ForegroundColor','b',...
        'FontName','Microsoft YaHei');
    uicontrol(panelHndl,...
        'Style','text',...
        'String','椎体直径[m]:',...
        'BackgroundColor',192/255*[1 1 1],...
        'FontSize',10,...
        'ForegroundColor','k',...
        'FontName','Microsoft YaHei',...
        'Units','normalized', ...
        'Position',[0.03,starth,w,h],...
        'HorizontalAlignment','Left');
    uicontrol(panelHndl,...
        'Style','text',...
        'String','椎体锥角[°]:',...
        'BackgroundColor',192/255*[1 1 1],...
        'FontSize',10,...
        'ForegroundColor','k',...
        'FontName','Microsoft YaHei',...
        'Units','normalized', ...
        'Position',[0.03,starth-h-space,w,h],...
        'HorizontalAlignment','Left');
    uicontrol(panelHndl,...
        'Style','text',...
        'String','椎体密度[kg/m3]:',...
        'BackgroundColor',192/255*[1 1 1],...
        'FontSize',10,...
        'ForegroundColor','k',...
        'FontName','Microsoft YaHei',...
        'Units','normalized', ...
        'Position',[0.03,starth-h*2-space*2,w,h],...
        'HorizontalAlignment','Left');
    uicontrol(panelHndl,...
        'Style','edit',...
        'String',num2str(diameter),...
        'BackgroundColor','w',...
        'FontSize',10,...
        'ForegroundColor','k',...
        'FontName','Microsoft YaHei',...
        'Units','normalized', ...
        'Position',[0.03+w,starth,w,h],...
        'HorizontalAlignment','Left',...
        'Tag','Diameter');
    uicontrol(panelHndl,...
        'Style','edit',...
        'String',num2str(tapeAngle),...
        'BackgroundColor','w',...
        'FontSize',10,...
        'ForegroundColor','k',...
        'FontName','Microsoft YaHei',...
        'Units','normalized', ...
        'Position',[0.03+w,starth-h-space,w,h],...
        'HorizontalAlignment','Left',...
        'Tag','TapeAngle');
    uicontrol(panelHndl,...
        'Style','edit',...
        'String',num2str(density),...
        'BackgroundColor','w',...
        'FontSize',10,...
        'ForegroundColor','k',...
        'FontName','Microsoft YaHei',...
        'Units','normalized', ...
        'Position',[0.03+w,starth-h*2-space*2,w,h],...
        'HorizontalAlignment','Left',...
        'Tag','Density');
elseif strcmp(arg1,'cone_cylinder')
    filename = 'cone_configuration.mat';
    if filechecker(workpath,filename)
        load([workpath,'\',filename])
    else
        diameter = 1;
        height = 1;
        tapeAngle = 90;
        density = 7800;
    end
    delete(findall(allchild(figHndl),'Title','物体参数'))
    h = 0.12;
    w = 0.45;
    starth = 0.78;
    space = 0.1;
    panelHndl = uipanel(figHndl,...
        'Title','物体参数', ...
        'BackgroundColor',192/255*[1 1 1],...
        'Units','normalized', ...
        'Position',[0.25,0.4,0.5,0.57],...
        'FontSize',10,...
        'ForegroundColor','b',...
        'FontName','Microsoft YaHei');
    uicontrol(panelHndl,...
        'Style','text',...
        'String','柱体直径[m]:',...
        'BackgroundColor',192/255*[1 1 1],...
        'FontSize',10,...
        'ForegroundColor','k',...
        'FontName','Microsoft YaHei',...
        'Units','normalized', ...
        'Position',[0.03,starth,w,h],...
        'HorizontalAlignment','Left');
    uicontrol(panelHndl,...
        'Style','text',...
        'String','无头柱体高度[m]:',...
        'BackgroundColor',192/255*[1 1 1],...
        'FontSize',10,...
        'ForegroundColor','k',...
        'FontName','Microsoft YaHei',...
        'Units','normalized', ...
        'Position',[0.03,starth-h-space,w,h],...
        'HorizontalAlignment','Left');
    uicontrol(panelHndl,...
        'Style','text',...
        'String','椎体锥角[°]:',...
        'BackgroundColor',192/255*[1 1 1],...
        'FontSize',10,...
        'ForegroundColor','k',...
        'FontName','Microsoft YaHei',...
        'Units','normalized', ...
        'Position',[0.03,starth-h*2-space*2,w,h],...
        'HorizontalAlignment','Left');
    uicontrol(panelHndl,...
        'Style','text',...
        'String','柱体密度[kg/m3]:',...
        'BackgroundColor',192/255*[1 1 1],...
        'FontSize',10,...
        'ForegroundColor','k',...
        'FontName','Microsoft YaHei',...
        'Units','normalized', ...
        'Position',[0.03,starth-h*3-space*3,w,h],...
        'HorizontalAlignment','Left');
    uicontrol(panelHndl,...
        'Style','edit',...
        'String',num2str(diameter),...
        'BackgroundColor','w',...
        'FontSize',10,...
        'ForegroundColor','k',...
        'FontName','Microsoft YaHei',...
        'Units','normalized', ...
        'Position',[0.03+w,starth,w,h],...
        'HorizontalAlignment','Left',...
        'Tag','Diameter');
    uicontrol(panelHndl,...
        'Style','edit',...
        'String',num2str(height),...
        'BackgroundColor','w',...
        'FontSize',10,...
        'ForegroundColor','k',...
        'FontName','Microsoft YaHei',...
        'Units','normalized', ...
        'Position',[0.03+w,starth-h-space,w,h],...
        'HorizontalAlignment','Left',...
        'Tag','Height');
    uicontrol(panelHndl,...
        'Style','edit',...
        'String',num2str(tapeAngle),...
        'BackgroundColor','w',...
        'FontSize',10,...
        'ForegroundColor','k',...
        'FontName','Microsoft YaHei',...
        'Units','normalized', ...
        'Position',[0.03+w,starth-h*2-space*2,w,h],...
        'HorizontalAlignment','Left',...
        'Tag','TapeAngle');
    uicontrol(panelHndl,...
        'Style','edit',...
        'String',num2str(density),...
        'BackgroundColor','w',...
        'FontSize',10,...
        'ForegroundColor','k',...
        'FontName','Microsoft YaHei',...
        'Units','normalized', ...
        'Position',[0.03+w,starth-h*3-space*3,w,h],...
        'HorizontalAlignment','Left',...
        'Tag','Density');
elseif strcmp(arg1,'sphere_cylinder')
    filename = 'sphere_cylinder_configuration.mat';
    if filechecker(workpath,filename)
        load([workpath,'\',filename])
    else
        diameter = 1;
        height = 1;
        density = 7800;
    end
    delete(findall(allchild(figHndl),'Title','物体参数'))
    h = 0.12;
    w = 0.45;
    starth = 0.78;
    space = 0.1;
    panelHndl = uipanel(figHndl,...
        'Title','物体参数', ...
        'BackgroundColor',192/255*[1 1 1],...
        'Units','normalized', ...
        'Position',[0.25,0.4,0.5,0.57],...
        'FontSize',10,...
        'ForegroundColor','b',...
        'FontName','Microsoft YaHei');
    uicontrol(panelHndl,...
        'Style','text',...
        'String','柱体直径[m]:',...
        'BackgroundColor',192/255*[1 1 1],...
        'FontSize',10,...
        'ForegroundColor','k',...
        'FontName','Microsoft YaHei',...
        'Units','normalized', ...
        'Position',[0.03,starth,w,h],...
        'HorizontalAlignment','Left');
    uicontrol(panelHndl,...
        'Style','text',...
        'String','无头柱体高度[m]:',...
        'BackgroundColor',192/255*[1 1 1],...
        'FontSize',10,...
        'ForegroundColor','k',...
        'FontName','Microsoft YaHei',...
        'Units','normalized', ...
        'Position',[0.03,starth-h-space,w,h],...
        'HorizontalAlignment','Left');
    uicontrol(panelHndl,...
        'Style','text',...
        'String','柱体密度[kg/m3]:',...
        'BackgroundColor',192/255*[1 1 1],...
        'FontSize',10,...
        'ForegroundColor','k',...
        'FontName','Microsoft YaHei',...
        'Units','normalized', ...
        'Position',[0.03,starth-h*2-space*2,w,h],...
        'HorizontalAlignment','Left');
    uicontrol(panelHndl,...
        'Style','edit',...
        'String',num2str(diameter),...
        'BackgroundColor','w',...
        'FontSize',10,...
        'ForegroundColor','k',...
        'FontName','Microsoft YaHei',...
        'Units','normalized', ...
        'Position',[0.03+w,starth,w,h],...
        'HorizontalAlignment','Left',...
        'Tag','Diameter');
    uicontrol(panelHndl,...
        'Style','edit',...
        'String',num2str(height),...
        'BackgroundColor','w',...
        'FontSize',10,...
        'ForegroundColor','k',...
        'FontName','Microsoft YaHei',...
        'Units','normalized', ...
        'Position',[0.03+w,starth-h-space,w,h],...
        'HorizontalAlignment','Left',...
        'Tag','Height');
    uicontrol(panelHndl,...
        'Style','edit',...
        'String',num2str(density),...
        'BackgroundColor','w',...
        'FontSize',10,...
        'ForegroundColor','k',...
        'FontName','Microsoft YaHei',...
        'Units','normalized', ...
        'Position',[0.03+w,starth-h*2-space*2,w,h],...
        'HorizontalAlignment','Left',...
        'Tag','Density');
end